### ISSUE TITLE
Unicorns

### ISSUE THREAD

**Issue by beatyt** [Briggsdf/Happilyy#1]
https://github.com/Briggsdf/Happilyy/blob/master/src/main/java/rest/test/happilyy/configuration/JDBCConfigration.java#L24

I think you have to re-initialize the repository after deleting those... else there will still be commit history.

Can use environment variables and placeholders to get around that. Ex:

application.properties
```
datasource.password=${datasource_password}
```

JDBCConfigration.java
```
@Value
private String datasourcePassword;
```

and then set that environment variable on your machine. Also let's you split your dev / prod databases while working.

**Comment by Briggsdf** [comment]
That’s actually the next lesson. Adding a properties file, we’re actually going to add  filter files and maven merge plugins based on username. So everyone can have their own files pointing to their own database and with their own configuration.  I.e: Debriggs.propeties. 


But what’s all this about commit history?

**Comment by beatyt** [comment]
Someone could still check out the old revision to see db creds. If it gets committed to git it's there forever unless you rebase.

**Comment by Briggsdf** [comment]
That is true, but if every user property file is pointed to a local database then it shouldn’t  be an issue. Also we can create a “common” filter file which would use value placeholders and then we can just pass the actual values when we deploy using  Harbor, Fargate, Heroku for whatever environment.   So something like Db.password={database_password} and then we can pass that value when we deploy. Locally that would be replaced with the value in your properties file(which the mvn plugin will merge into the commons and then the application properties) .

**Comment by beatyt** [comment]
Yeah in the future it will be fine.

Basically, don't put anything important in the current one lol.

**Comment by Briggsdf** [comment]
Steal Matt’s credit card and let’s buy some private repos.

**Comment by beatyt** [comment]
https://github.com/pricing

No CC needed
